name: Netlify Deploy

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Build and Deploy to Netlify
        run: |
          # Replace 'your-netlify-site-name' with your actual Netlify site name
          netlify sites deploy --prod --site your-netlify-site-name
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
